<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ActualizarClienteEBSAdapter.wsdl"/>
      <rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarClienteEBSAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ActualizarClienteEBSAdapter.wsdl"/>
      <rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarClienteEBSAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [THU APR 30 16:11:30 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarClienteEBSAdapter"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Oportunidades/ActualizarClienteEBSAdapter"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl db plt xsd wsdl tns xp20 bpws mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <db:InputParameters>
      <xsl:if test="/db:InputParameters/db:P_ORGANIZATION_NAME">
        <db:P_ORGANIZATION_NAME>
          <xsl:if test="/db:InputParameters/db:P_ORGANIZATION_NAME/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_ORGANIZATION_NAME/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_ORGANIZATION_NAME"/>
        </db:P_ORGANIZATION_NAME>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_JGZZ_FISCAL_CODE">
        <db:P_JGZZ_FISCAL_CODE>
          <xsl:if test="/db:InputParameters/db:P_JGZZ_FISCAL_CODE/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_JGZZ_FISCAL_CODE/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_JGZZ_FISCAL_CODE"/>
        </db:P_JGZZ_FISCAL_CODE>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_COUNTRY">
        <db:P_COUNTRY>
          <xsl:if test="/db:InputParameters/db:P_COUNTRY/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_COUNTRY/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_COUNTRY"/>
        </db:P_COUNTRY>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_ADDRESS1">
        <db:P_ADDRESS1>
          <xsl:if test="/db:InputParameters/db:P_ADDRESS1/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_ADDRESS1/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_ADDRESS1"/>
        </db:P_ADDRESS1>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_ADDRESS2">
        <db:P_ADDRESS2>
          <xsl:if test="/db:InputParameters/db:P_ADDRESS2/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_ADDRESS2/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_ADDRESS2"/>
        </db:P_ADDRESS2>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_CITY">
        <db:P_CITY>
          <xsl:if test="/db:InputParameters/db:P_CITY/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_CITY/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_CITY"/>
        </db:P_CITY>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_STATE">
        <db:P_STATE>
          <xsl:if test="/db:InputParameters/db:P_STATE/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_STATE/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_STATE"/>
        </db:P_STATE>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_CODIGO_SECTOR_INDUSTRIAL">
        <db:P_CODIGO_SECTOR_INDUSTRIAL>
          <xsl:if test="/db:InputParameters/db:P_CODIGO_SECTOR_INDUSTRIAL/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_CODIGO_SECTOR_INDUSTRIAL/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_CODIGO_SECTOR_INDUSTRIAL"/>
        </db:P_CODIGO_SECTOR_INDUSTRIAL>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_JOB_TITLE">
        <db:P_JOB_TITLE>
          <xsl:if test="/db:InputParameters/db:P_JOB_TITLE/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_JOB_TITLE/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_JOB_TITLE"/>
        </db:P_JOB_TITLE>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_JOB_TITLE_CODE">
        <db:P_JOB_TITLE_CODE>
          <xsl:if test="/db:InputParameters/db:P_JOB_TITLE_CODE/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_JOB_TITLE_CODE/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_JOB_TITLE_CODE"/>
        </db:P_JOB_TITLE_CODE>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_PERSON_FIRST_NAME">
        <db:P_PERSON_FIRST_NAME>
          <xsl:if test="/db:InputParameters/db:P_PERSON_FIRST_NAME/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_PERSON_FIRST_NAME/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_PERSON_FIRST_NAME"/>
        </db:P_PERSON_FIRST_NAME>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_PERSON_LAST_NAME">
        <db:P_PERSON_LAST_NAME>
          <xsl:if test="/db:InputParameters/db:P_PERSON_LAST_NAME/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_PERSON_LAST_NAME/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_PERSON_LAST_NAME"/>
        </db:P_PERSON_LAST_NAME>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_PHONE_NUMBER_PERSON">
        <db:P_PHONE_NUMBER_PERSON>
          <xsl:if test="/db:InputParameters/db:P_PHONE_NUMBER_PERSON/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_PHONE_NUMBER_PERSON/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_PHONE_NUMBER_PERSON"/>
        </db:P_PHONE_NUMBER_PERSON>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_PHONE_NUMBER_ORG">
        <db:P_PHONE_NUMBER_ORG>
          <xsl:if test="/db:InputParameters/db:P_PHONE_NUMBER_ORG/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_PHONE_NUMBER_ORG/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_PHONE_NUMBER_ORG"/>
        </db:P_PHONE_NUMBER_ORG>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_EMAIL_ADDRESS">
        <db:P_EMAIL_ADDRESS>
          <xsl:if test="/db:InputParameters/db:P_EMAIL_ADDRESS/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_EMAIL_ADDRESS/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_EMAIL_ADDRESS"/>
        </db:P_EMAIL_ADDRESS>
      </xsl:if>
      <xsl:if test="/db:InputParameters/db:P_ID_CONTACTO">
        <db:P_ID_CONTACTO>
          <xsl:if test="/db:InputParameters/db:P_ID_CONTACTO/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/db:InputParameters/db:P_ID_CONTACTO/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/db:InputParameters/db:P_ID_CONTACTO"/>
        </db:P_ID_CONTACTO>
      </xsl:if>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>
