<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ActualizarOportunidadEBSWS.wsdl"/>
      <rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarOportunidadEBSAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ActualizarOportunidadEBSAdapter.wsdl"/>
      <rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarOportunidadEBSAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED FEB 11 16:56:17 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://oracle.com/sca/soapservice/ServiciosEBS/Oportunidades/ActualizarOportunidadEBSWS"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:inp1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarOportunidadEBSAdapter"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Oportunidades/ActualizarOportunidadEBSAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns inp1 xsd wsdl ns0 plt bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <inp1:InputParameters>
      <inp1:L_USER_NAME>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_USER_NAME/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_USER_NAME"/>
      </inp1:L_USER_NAME>
      <inp1:I_LEAD_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:I_LEAD_ID/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:I_LEAD_ID"/>
      </inp1:I_LEAD_ID>
      <inp1:L_DESCRIPTION>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_DESCRIPTION/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_DESCRIPTION"/>
      </inp1:L_DESCRIPTION>
      <inp1:L_SALES_STAGE_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_SALES_STAGE_ID/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_SALES_STAGE_ID"/>
      </inp1:L_SALES_STAGE_ID>
      <inp1:L_STATUS_CODE>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_STATUS_CODE/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_STATUS_CODE"/>
      </inp1:L_STATUS_CODE>
      <inp1:L_TOTAL_AMOUNT>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_TOTAL_AMOUNT/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_TOTAL_AMOUNT"/>
      </inp1:L_TOTAL_AMOUNT>
      <inp1:L_CHANNEL_CODE>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_CHANNEL_CODE/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_CHANNEL_CODE"/>
      </inp1:L_CHANNEL_CODE>
      <inp1:L_DECISION_DATE>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_DECISION_DATE/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_DECISION_DATE"/>
      </inp1:L_DECISION_DATE>
      <inp1:L_CLOSE_REASON>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_CLOSE_REASON/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_CLOSE_REASON"/>
      </inp1:L_CLOSE_REASON>
      <inp1:L_CURRENCY_CODE>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_CURRENCY_CODE/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_CURRENCY_CODE"/>
      </inp1:L_CURRENCY_CODE>
      <inp1:L_PROB_OPORCLIE>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_PROB_OPORCLIE/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_PROB_OPORCLIE"/>
      </inp1:L_PROB_OPORCLIE>
      <inp1:L_PROB_OPORIMO>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_PROB_OPORIMO/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_PROB_OPORIMO"/>
      </inp1:L_PROB_OPORIMO>
      <inp1:L_ID_ARCHIVO_ORD_COMPRA>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_ID_ARCHIVO_ORD_COMPRA/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_ID_ARCHIVO_ORD_COMPRA"/>
      </inp1:L_ID_ARCHIVO_ORD_COMPRA>
      <inp1:L_NOMBRE_ARCHIVO_ORD_COMPRA>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_NOMBRE_ARCHIVO_ORD_COMPRA/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/inp1:InputParameters/inp1:L_NOMBRE_ARCHIVO_ORD_COMPRA"/>
      </inp1:L_NOMBRE_ARCHIVO_ORD_COMPRA>
      <inp1:L_LINE_TBL_BPM>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/inp1:InputParameters/inp1:L_LINE_TBL_BPM/@xsi:nil"/>
        </xsl:attribute>
        <xsl:for-each select="/inp1:InputParameters/inp1:L_LINE_TBL_BPM/inp1:L_LINE_TBL_BPM_ITEM">
          <inp1:L_LINE_TBL_BPM_ITEM>
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="@xsi:nil"/>
            </xsl:attribute>
            <inp1:LEAD_LINE_ID>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="inp1:LEAD_LINE_ID/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="inp1:LEAD_LINE_ID"/>
            </inp1:LEAD_LINE_ID>
            <inp1:RETURN_STATUS>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="inp1:RETURN_STATUS/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="inp1:RETURN_STATUS"/>
            </inp1:RETURN_STATUS>
            <inp1:INVENTORY_ITEM_ID>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="inp1:INVENTORY_ITEM_ID/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="inp1:INVENTORY_ITEM_ID"/>
            </inp1:INVENTORY_ITEM_ID>
            <inp1:UOM_CODE>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="inp1:UOM_CODE/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="inp1:UOM_CODE"/>
            </inp1:UOM_CODE>
            <inp1:QUANTITY>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="inp1:QUANTITY/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="inp1:QUANTITY"/>
            </inp1:QUANTITY>
            <inp1:TOTAL_AMOUNT>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="inp1:TOTAL_AMOUNT/@xsi:nil"/>
              </xsl:attribute>
              <xsl:value-of select="inp1:TOTAL_AMOUNT"/>
            </inp1:TOTAL_AMOUNT>
          </inp1:L_LINE_TBL_BPM_ITEM>
        </xsl:for-each>
      </inp1:L_LINE_TBL_BPM>
    </inp1:InputParameters>
  </xsl:template>
</xsl:stylesheet>
