<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../OportunidadesEBS.wsdl"/>
      <rootElement name="oportunidadesNombreEtapaEstado" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ConsultaOportunidadesByNombreEtapaByEstadoAdapter.wsdl"/>
      <rootElement name="ConsultaOportunidadesByNombreEtapaByEstadoAdapterInput" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaOportunidadesByNombreEtapaByEstadoAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [TUE JUN 21 17:51:57 COT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Oportunidades/ConsultaOportunidadesByNombreEtapaByEstadoAdapter"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaOportunidadesByNombreEtapaByEstadoAdapter"
                exclude-result-prefixes="xsi xsl soap tns xsd plt ns0 wsdl db xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <db:ConsultaOportunidadesByNombreEtapaByEstadoAdapterInput>
      <xsl:choose>
        <xsl:when test='(/tns:oportunidadesNombreEtapaEstado/estado = "") or not(boolean(/tns:oportunidadesNombreEtapaEstado/estado))'>
          <db:v_estado>
            <xsl:text disable-output-escaping="no">%</xsl:text>
          </db:v_estado>
        </xsl:when>
        <xsl:otherwise>
          <db:v_estado>
            <xsl:value-of select="/tns:oportunidadesNombreEtapaEstado/estado"/>
          </db:v_estado>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test='(/tns:oportunidadesNombreEtapaEstado/nombre = "") or not(boolean(/tns:oportunidadesNombreEtapaEstado/nombre))'>
		  <db:v_nombre_oportunidad>
            <xsl:text disable-output-escaping="no">%</xsl:text>
          </db:v_nombre_oportunidad>
        </xsl:when>
        <xsl:otherwise>
          <db:v_nombre_oportunidad>
            <xsl:value-of select="/tns:oportunidadesNombreEtapaEstado/nombre"/>
          </db:v_nombre_oportunidad>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
	    <xsl:when test='(/tns:oportunidadesNombreEtapaEstado/etapa = "") or not(boolean(/tns:oportunidadesNombreEtapaEstado/etapa))'>
          <db:v_etapa>
            <xsl:text disable-output-escaping="no">%</xsl:text>
          </db:v_etapa>
        </xsl:when>
        <xsl:otherwise>
          <db:v_etapa>
            <xsl:value-of select="/tns:oportunidadesNombreEtapaEstado/etapa"/>
          </db:v_etapa>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test='(/tns:oportunidadesNombreEtapaEstado/idAsesor = "") or not(boolean(/tns:oportunidadesNombreEtapaEstado/idAsesor))'>
            <db:v_id_asesor>
				<xsl:text disable-output-escaping="no">%</xsl:text>
			</db:v_id_asesor>
        </xsl:when>
         <xsl:otherwise>
          <db:v_id_asesor>
            <xsl:value-of select="/tns:oportunidadesNombreEtapaEstado/idAsesor"/>
          </db:v_id_asesor>
        </xsl:otherwise>
      </xsl:choose>
    </db:ConsultaOportunidadesByNombreEtapaByEstadoAdapterInput>
  </xsl:template>
</xsl:stylesheet>
