<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ActualizarOportunidadEBSAdapter.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarOportunidadEBSAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ActualizarOportunidadEBSWS.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarOportunidadEBSAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED FEB 11 16:57:20 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns0="http://oracle.com/sca/soapservice/ServiciosEBS/Oportunidades/ActualizarOportunidadEBSWS"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ActualizarOportunidadEBSAdapter"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Oportunidades/ActualizarOportunidadEBSAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl db tns plt xsd wsdl ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <db:OutputParameters>
      <xsl:if test="/db:OutputParameters/db:L_LINE_TBL_OUT">
        <db:L_LINE_TBL_OUT>
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/db:OutputParameters/db:L_LINE_TBL_OUT/@xsi:nil"/>
          </xsl:attribute>
          <xsl:for-each select="/db:OutputParameters/db:L_LINE_TBL_OUT/db:L_LINE_TBL_BPM_ITEM">
            <db:L_LINE_TBL_BPM_ITEM>
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="@xsi:nil"/>
              </xsl:attribute>
              <db:LEAD_LINE_ID>
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="db:LEAD_LINE_ID/@xsi:nil"/>
                </xsl:attribute>
                <xsl:value-of select="db:LEAD_LINE_ID"/>
              </db:LEAD_LINE_ID>
              <db:RETURN_STATUS>
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="db:RETURN_STATUS/@xsi:nil"/>
                </xsl:attribute>
                <xsl:value-of select="db:RETURN_STATUS"/>
              </db:RETURN_STATUS>
              <db:INVENTORY_ITEM_ID>
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="db:INVENTORY_ITEM_ID/@xsi:nil"/>
                </xsl:attribute>
                <xsl:value-of select="db:INVENTORY_ITEM_ID"/>
              </db:INVENTORY_ITEM_ID>
              <db:UOM_CODE>
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="db:UOM_CODE/@xsi:nil"/>
                </xsl:attribute>
                <xsl:value-of select="db:UOM_CODE"/>
              </db:UOM_CODE>
              <db:QUANTITY>
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="db:QUANTITY/@xsi:nil"/>
                </xsl:attribute>
                <xsl:value-of select="db:QUANTITY"/>
              </db:QUANTITY>
              <db:TOTAL_AMOUNT>
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="db:TOTAL_AMOUNT/@xsi:nil"/>
                </xsl:attribute>
                <xsl:value-of select="db:TOTAL_AMOUNT"/>
              </db:TOTAL_AMOUNT>
            </db:L_LINE_TBL_BPM_ITEM>
          </xsl:for-each>
        </db:L_LINE_TBL_OUT>
      </xsl:if>
      <db:O_LEAD_ID>
        <xsl:attribute name="xsi:nil">
          <xsl:value-of select="/db:OutputParameters/db:O_LEAD_ID/@xsi:nil"/>
        </xsl:attribute>
        <xsl:value-of select="/db:OutputParameters/db:O_LEAD_ID"/>
      </db:O_LEAD_ID>
    </db:OutputParameters>
  </xsl:template>
</xsl:stylesheet>
