SELECT HZP1.PARTY_NAME,
  HZP1.PERSON_LAST_NAME,
  HZP1.PERSON_MIDDLE_NAME,
  HZP1.PERSON_FIRST_NAME,
  (SELECT hzoc.PHONE_NUMBER
  FROM HZ_CONTACT_POINTS hzoc
  WHERE hzoc.OWNER_TABLE_ID = HZP1.PARTY_ID
  AND hzoc.CONTACT_POINT_TYPE LIKE '%PHONE%'
  AND hzoc.PHONE_LINE_TYPE LIKE '%GEN%'
  AND ROWNUM = 1
  ) PHONE_NUMBER,
  (SELECT hzoc.PHONE_NUMBER
  FROM HZ_CONTACT_POINTS hzoc
  WHERE hzoc.OWNER_TABLE_ID = HZP1.PARTY_ID
  AND hzoc.CONTACT_POINT_TYPE LIKE '%PHONE%'
  AND hzoc.PHONE_LINE_TYPE LIKE '%MOBILE%'
  AND ROWNUM = 1
  ) RAW_PHONE_NUMBER,
  HZP1.EMAIL_ADDRESS,
  HZ_RELATIONSHIPS.ATTRIBUTE1 AS JOB_TITLE,
  'CONTACT_OF'                AS RELACION,
  HZP2.PARTY_NAME,
  HZP2.JGZZ_FISCAL_CODE AS NIT
FROM HZ_RELATIONSHIPS,
  HZ_PARTIES HZP1,
  HZ_PARTIES HZP2
WHERE RELATIONSHIP_CODE LIKE '%CONTACT_OF%'
AND HZP1.PARTY_ID = HZ_RELATIONSHIPS.SUBJECT_ID
AND HZP2.PARTY_ID = HZ_RELATIONSHIPS.OBJECT_ID
AND HZP1.PARTY_TYPE LIKE '%PERSON%'
AND HZP2.JGZZ_FISCAL_CODE LIKE DECODE(#v_nit_empresa, '', '%', TO_CHAR('%'
  || #v_nit_empresa_2
  || '%'))