<?binding.jca ConsultarContactosPorCliente_db.jca?>
<wsdl:definitions name="ConsultarContactosPorCliente" targetNamespace="http://com.imocom.intelcom.ws.ebs.interfaces/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContactosPorCliente" xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConsultarContactosPorCliente_plt">
        <plt:role name="ConsultarContactosPorCliente_role">
            <plt:portType name="tns:ConsultarContactosPorCliente_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContactosPorCliente" schemaLocation="xsd/ConsultarContactosPorCliente.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarContactosPorClienteInput_msg">
        <wsdl:part name="ConsultarContactosPorClienteInput_msg" element="db:ConsultarContactosPorClienteInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarContactosPorClienteOutputCollection_msg">
        <wsdl:part name="ConsultarContactosPorClienteOutputCollection" element="db:ConsultarContactosPorClienteOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarContactosPorCliente_ptt">
        <wsdl:operation name="ConsultarContactosPorCliente">
            <wsdl:input message="tns:ConsultarContactosPorClienteInput_msg"/>
            <wsdl:output message="tns:ConsultarContactosPorClienteOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
