<?binding.jca ConsultaClientesByFiltrosEBSAdapter_db.jca?>
<wsdl:definitions name="ConsultaClientesByFiltrosEBSAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Clientes/ConsultaClientesByFiltrosEBSAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaClientesByFiltrosEBSAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Clientes/ConsultaClientesByFiltrosEBSAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConsultaClientesByFiltrosEBSAdapter_plt">
        <plt:role name="ConsultaClientesByFiltrosEBSAdapter_role">
            <plt:portType name="tns:ConsultaClientesByFiltrosEBSAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaClientesByFiltrosEBSAdapter" schemaLocation="xsd/ConsultaClientesByFiltrosEBSAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaClientesByFiltrosEBSAdapterInput_msg">
        <wsdl:part name="ConsultaClientesByFiltrosEBSAdapterInput_msg" element="db:ConsultaClientesByFiltrosEBSAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaClientesByFiltrosEBSAdapterOutputCollection_msg">
        <wsdl:part name="ConsultaClientesByFiltrosEBSAdapterOutputCollection" element="db:ConsultaClientesByFiltrosEBSAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaClientesByFiltrosEBSAdapter_ptt">
        <wsdl:operation name="ConsultaClientesByFiltrosEBSAdapter">
            <wsdl:input message="tns:ConsultaClientesByFiltrosEBSAdapterInput_msg"/>
            <wsdl:output message="tns:ConsultaClientesByFiltrosEBSAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
