<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsultaDatosCarteraByNitEBSAdapter.wsdl"/>
      <rootElement name="ConsultaDatosCarteraByNitEBSAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaDatosCarteraByNitEBSAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../CarteraEBS.wsdl"/>
      <rootElement name="consultaDatosCarteraResponse" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [TUE FEB 17 14:13:07 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaDatosCarteraByNitEBSAdapter"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Cartera/ConsultaDatosCarteraByNitEBSAdapter"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl db tns plt wsdl xsd soap ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns0:consultaDatosCarteraResponse>
      <return>
        <carteras>
          <nitCliente>
            <xsl:value-of select="/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput/db:CUSTOMER_NUMBER"/>
          </nitCliente>
          <nombreCliente>
            <xsl:value-of select="/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput/db:NOMBRE_CLIENTE"/>
          </nombreCliente>
          <cupoCredito>
            <xsl:value-of select='concat("$",format-number(/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput/db:CUPO_CREDITO,"###,###")," COP")'/>
          </cupoCredito>
          <tipoCliente>
            <xsl:value-of select="/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput/db:TIPOCLIE"/>
          </tipoCliente>
          <cupoCreditoDisponible>
            <xsl:value-of select="concat(format-number(/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput/db:CUPO_CREDITO - sum(/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput/db:sub_TOTAL_CARTERA),&quot;###,###&quot;),'$')"/>
          </cupoCreditoDisponible>
          <totalCartera>
            <xsl:value-of select="concat('$',format-number(sum(/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput/db:sub_TOTAL_CARTERA),&quot;###,###&quot;))"/>
          </totalCartera>
          <totalCarteraAsesor>
            <xsl:value-of select="concat('$',format-number(sum(/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput/db:valor_cart_vendedor),&quot;###,###&quot;))"/>
          </totalCarteraAsesor>
        </carteras>
        <xsl:for-each select="/db:ConsultaDatosCarteraByNitEBSAdapterOutputCollection/db:ConsultaDatosCarteraByNitEBSAdapterOutput">
          <facturas>
            <idFactura>
              <xsl:value-of select="db:NUMERO_DOC"/>
            </idFactura>
            <fechaVencimiento>
              <xsl:value-of select='xp20:format-dateTime(db:FECHA_VENCIMIENTO,"[D01]/[M01]/[Y0001]")'/>
            </fechaVencimiento>
            <nroDiasVencimiento>
              <xsl:value-of select="db:DIAS_VENCIDOS"/>
            </nroDiasVencimiento>
            <valorFactura>
              <xsl:value-of select="concat('$',format-number(db:sub_TOTAL_CARTERA,&quot;###,###&quot;))"/>
            </valorFactura>
            <valorVencido>
              <xsl:value-of select='concat("$",format-number(db:VALOR_VENCIDO,"###,###")," COP")'/>
            </valorVencido>
            <centroCosto>
              <xsl:value-of select="db:LINEA"/>
            </centroCosto>
            <valorPorVencer>
              <xsl:value-of select="db:VALOR_POR_VENCER"/>
            </valorPorVencer>
          </facturas>
        </xsl:for-each>
      </return>
    </ns0:consultaDatosCarteraResponse>
  </xsl:template>
</xsl:stylesheet>
