<?binding.jca consultarModelosPorMarca_db.jca?>
<wsdl:definitions name="consultarModelosPorMarca" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Productos/consultarModelosPorMarca" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/consultarModelosPorMarca" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Productos/consultarModelosPorMarca" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="consultarModelosPorMarca_plt">
        <plt:role name="consultarModelosPorMarca_role">
            <plt:portType name="tns:consultarModelosPorMarca_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultarModelosPorMarca" schemaLocation="xsd/consultarModelosPorMarca.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="consultarModelosPorMarcaInput_msg">
        <wsdl:part name="consultarModelosPorMarcaInput_msg" element="db:consultarModelosPorMarcaInput"/>
    </wsdl:message>
    <wsdl:message name="consultarModelosPorMarcaOutputCollection_msg">
        <wsdl:part name="consultarModelosPorMarcaOutputCollection" element="db:consultarModelosPorMarcaOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="consultarModelosPorMarca_ptt">
        <wsdl:operation name="consultarModelosPorMarca">
            <wsdl:input message="tns:consultarModelosPorMarcaInput_msg"/>
            <wsdl:output message="tns:consultarModelosPorMarcaOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
