<?binding.jca ConsultaProductosPendietesPorFacturarEBSAdapter_db.jca?>
<wsdl:definitions name="ConsultaProductosPendietesPorFacturarEBSAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Productos/ConsultaProductosPendietesPorFacturarEBSAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaProductosPendietesPorFacturarEBSAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Productos/ConsultaProductosPendietesPorFacturarEBSAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConsultaProductosPendietesPorFacturarEBSAdapter_plt">
        <plt:role name="ConsultaProductosPendietesPorFacturarEBSAdapter_role">
            <plt:portType name="tns:ConsultaProductosPendietesPorFacturarEBSAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaProductosPendietesPorFacturarEBSAdapter" schemaLocation="xsd/ConsultaProductosPendietesPorFacturarEBSAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaProductosPendietesPorFacturarEBSAdapterInput_msg">
        <wsdl:part name="ConsultaProductosPendietesPorFacturarEBSAdapterInput_msg" element="db:ConsultaProductosPendietesPorFacturarEBSAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaProductosPendietesPorFacturarEBSAdapterOutputCollection_msg">
        <wsdl:part name="ConsultaProductosPendietesPorFacturarEBSAdapterOutputCollection" element="db:ConsultaProductosPendietesPorFacturarEBSAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaProductosPendietesPorFacturarEBSAdapter_ptt">
        <wsdl:operation name="ConsultaProductosPendietesPorFacturarEBSAdapter">
            <wsdl:input message="tns:ConsultaProductosPendietesPorFacturarEBSAdapterInput_msg"/>
            <wsdl:output message="tns:ConsultaProductosPendietesPorFacturarEBSAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
