<?binding.jca ProductoCotizableAutomaticamente_db.jca?>
<wsdl:definitions name="ProductoCotizableAutomaticamente" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Productos/ProductoCotizableAutomaticamente" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ProductoCotizableAutomaticamente" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Productos/ProductoCotizableAutomaticamente" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ProductoCotizableAutomaticamente_plt">
        <plt:role name="ProductoCotizableAutomaticamente_role">
            <plt:portType name="tns:ProductoCotizableAutomaticamente_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProductoCotizableAutomaticamente" schemaLocation="xsd/ProductoCotizableAutomaticamente.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ProductoCotizableAutomaticamenteInput_msg">
        <wsdl:part name="ProductoCotizableAutomaticamenteInput_msg" element="db:ProductoCotizableAutomaticamenteInput"/>
    </wsdl:message>
    <wsdl:message name="ProductoCotizableAutomaticamenteOutputCollection_msg">
        <wsdl:part name="ProductoCotizableAutomaticamenteOutputCollection" element="db:ProductoCotizableAutomaticamenteOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ProductoCotizableAutomaticamente_ptt">
        <wsdl:operation name="ProductoCotizableAutomaticamente">
            <wsdl:input message="tns:ProductoCotizableAutomaticamenteInput_msg"/>
            <wsdl:output message="tns:ProductoCotizableAutomaticamenteOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
