<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../CotizacionesBPM.wsdl"/>
      <rootElement name="actualizacionCotizaciones" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://192.168.0.25:8001/soa-infra/services/default/comercialProject/ProcesoCotizaciones.wsdl"/>
      <rootElement name="ActualizarCotizacionAutomatica" namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ProcesoCotizaciones"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [THU MAR 05 19:27:54 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://www.imocom.com.co/soa/xsd/producto"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns6="http://www.imocom.com.co/soa/xsd/cotizacion"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns0="http://xmlns.oracle.com/bpmn/bpmnProcess/ProcesoCotizaciones"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap tns xsd SOAP-ENC plnk wsdl ns1 tns6 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns0:ActualizarCotizacionAutomatica>
      <tns6:SolicitudCotizacion>
        <tns6:asesor>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/nombreUsuario"/>
        </tns6:asesor>
        <tns6:codigoCotizacion>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/codigo"/>
        </tns6:codigoCotizacion>
        <tns6:idOportunidad>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/idOportunidad"/>
        </tns6:idOportunidad>
        <tns6:nombreOportunidad>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/nombreOportunidad"/>
        </tns6:nombreOportunidad>
        <tns6:idCliente>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/idCliente"/>
        </tns6:idCliente>
        <tns6:nombreCliente>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/nombreCliente"/>
        </tns6:nombreCliente>
        <tns6:idIncoterm>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/idInconterm"/>
        </tns6:idIncoterm>
        <tns6:fechaLimiteGeneracion>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/fechLimiteGeneracion"/>
        </tns6:fechaLimiteGeneracion>
        <tns6:tipoOferta>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/tipoOferta"/>
        </tns6:tipoOferta>
        <tns6:idEstadoCotizacion>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/idEstadoCotizacion"/>
        </tns6:idEstadoCotizacion>
        <tns6:ObservAsesor>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/observAsesor"/>
        </tns6:ObservAsesor>
        <tns6:idArchivoAdjSolicitud>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/idArchivoAdjSolicitud"/>
        </tns6:idArchivoAdjSolicitud>
        <tns6:nombreArchivoAdjSolicitud>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/nombreArchivoAdjSolicitud"/>
        </tns6:nombreArchivoAdjSolicitud>
        <tns6:urlArchivoAdjunto>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/urlContentArchivoAdjSolicitud"/>
        </tns6:urlArchivoAdjunto>
        <tns6:idTipoMoneda>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/idTipoMoneda"/>
        </tns6:idTipoMoneda>
        <tns6:valorTotal>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/valorTotal"/>
        </tns6:valorTotal>
        <tns6:fechaSolicitud>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/fechaSolicitud"/>
        </tns6:fechaSolicitud>
        <tns6:idVisitaGenerador>
          <xsl:value-of select="/tns:actualizacionCotizaciones/request/idVisitaGenerador"/>
        </tns6:idVisitaGenerador>
      </tns6:SolicitudCotizacion>
    </ns0:ActualizarCotizacionAutomatica>
  </xsl:template>
</xsl:stylesheet>
