<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ProcesosBPM.wsdl"/>
      <rootElement name="actualizacionCliente" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://192.168.0.25:8001/soa-infra/services/default/comercialProject/ActualizacionClienteInterface.wsdl"/>
      <rootElement name="actualizacionCliente" namespace="http://www.imocom.com.co/soa/xsd/gestionVisita"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 150407.0554.0203) AT [TUE JUN 02 07:25:02 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns1="http://www.imocom.com.co/soa/xsd/oportunidad"
                xmlns:ns2="http://www.imocom.com.co/soa/xsd/prospecto"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns4="http://www.imocom.com.co/soa/xsd/visita"
                xmlns:ns5="http://www.imocom.com.co/soa/xsd/usuario"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://oracle.com/sca/soapservice/ImocomBPM/comercialProject/ActualizacionClienteInterface"
                xmlns:ns3="http://www.imocom.com.co/soa/xsd/generico"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:inp1="http://www.imocom.com.co/soa/xsd/gestionVisita"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap tns xsd ns1 ns2 ns4 ns5 wsdl ns0 ns3 inp1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <inp1:actualizacionCliente>
      <inp1:nombreUsuario>
        <xsl:value-of select="/tns:actualizacionCliente/request/nombreUsuario"/>
      </inp1:nombreUsuario>
      <inp1:actualizacionCliente>
        <ns2:nitCliente>
          <xsl:value-of select="/tns:actualizacionCliente/request/nitClienteProspecto"/>
        </ns2:nitCliente>
        <ns2:nombreCliente>
          <xsl:value-of select="/tns:actualizacionCliente/request/nombreClienteProspecto"/>
        </ns2:nombreCliente>
        <ns2:nombreRepresentanteLegal>
          <xsl:value-of select="/tns:actualizacionCliente/request/nombreRepresentantelegal"/>
        </ns2:nombreRepresentanteLegal>
        <ns2:cedulaRepresentanteLegal>
          <xsl:value-of select="/tns:actualizacionCliente/request/cedulaRepresentantelegal"/>
        </ns2:cedulaRepresentanteLegal>
        <ns2:nombreGerenteGeneral>
          <xsl:value-of select="/tns:actualizacionCliente/request/nombreGerentelegal"/>
        </ns2:nombreGerenteGeneral>
        <ns2:cedulaGerenteGeneral>
          <xsl:value-of select="/tns:actualizacionCliente/request/cedulaGerentelegal"/>
        </ns2:cedulaGerenteGeneral>
        <ns2:contactoActualizar>
          <ns2:contacto>
            <ns2:nombreContacto>
              <xsl:value-of select="/tns:actualizacionCliente/request/nombreContactoProspecto"/>
            </ns2:nombreContacto>
            <ns2:apellidoContacto>
              <xsl:value-of select="/tns:actualizacionCliente/request/apellidoCliente"/>
            </ns2:apellidoContacto>
            <ns2:idCargo>
              <xsl:value-of select="/tns:actualizacionCliente/request/idCargoContactoProspecto"/>
            </ns2:idCargo>
            <ns2:cargo>
              <xsl:value-of select="/tns:actualizacionCliente/request/cargoContactoProspecto"/>
            </ns2:cargo>
            <ns2:telefonoContacto>
              <xsl:value-of select="/tns:actualizacionCliente/request/telefonoContactoProspecto"/>
            </ns2:telefonoContacto>
            <ns2:codigoAreaTelContacto>
              <xsl:value-of select="/tns:actualizacionCliente/request/indicativoContacto"/>
            </ns2:codigoAreaTelContacto>
            <ns2:celularContacto>
              <xsl:value-of select="/tns:actualizacionCliente/request/celularContactoProspecto"/>
            </ns2:celularContacto>
            <ns2:correoContacto>
              <xsl:value-of select="/tns:actualizacionCliente/request/correoContactoProspecto"/>
            </ns2:correoContacto>
          </ns2:contacto>
          <ns2:idContacto>
            <xsl:value-of select="/tns:actualizacionCliente/request/idContactoProspecto"/>
          </ns2:idContacto>
        </ns2:contactoActualizar>
        <ns2:direccionActualizar>
          <ns2:idPais>
            <xsl:value-of select="/tns:actualizacionCliente/request/idPaisDireccionProspecto"/>
          </ns2:idPais>
          <ns2:nombrePais>
            <xsl:value-of select="/tns:actualizacionCliente/request/nombrePaisDireccionProspecto"/>
          </ns2:nombrePais>
          <ns2:idDepartamento>
            <xsl:value-of select="/tns:actualizacionCliente/request/idDepartamentoDireccionProspecto"/>
          </ns2:idDepartamento>
          <ns2:nombreDepartamento>
            <xsl:value-of select="/tns:actualizacionCliente/request/nombreDepartamentoDireccionProspecto"/>
          </ns2:nombreDepartamento>
          <ns2:idCiudad>
            <xsl:value-of select="/tns:actualizacionCliente/request/idCiudadDireccionProspecto"/>
          </ns2:idCiudad>
          <ns2:ciudad>
            <xsl:value-of select="/tns:actualizacionCliente/request/ciudadDireccionProspecto"/>
          </ns2:ciudad>
          <ns2:direccion>
            <xsl:value-of select="/tns:actualizacionCliente/request/direccionDireccionProspecto"/>
          </ns2:direccion>
          <ns2:telefonoPrincipal>
            <xsl:value-of select="/tns:actualizacionCliente/request/telefonoPrincipalDireccionProspecto"/>
          </ns2:telefonoPrincipal>
          <ns2:codigoAreaTelPrincipal>
            <xsl:value-of select="/tns:actualizacionCliente/request/indicativo"/>
          </ns2:codigoAreaTelPrincipal>
        </ns2:direccionActualizar>
        <ns2:sectorIndustrialActualizar>
          <ns2:idSectorIndustrial>
            <xsl:value-of select="/tns:actualizacionCliente/request/idSectorIndustrialProspecto"/>
          </ns2:idSectorIndustrial>
          <ns2:nombreSectorIndustrial>
            <xsl:value-of select="/tns:actualizacionCliente/request/nombreSectorIndustriaProspecto"/>
          </ns2:nombreSectorIndustrial>
        </ns2:sectorIndustrialActualizar>
        <ns2:lineaActualizar>
          <ns2:idLinea>
            <xsl:value-of select="/tns:actualizacionCliente/request/idLineaProspecto"/>
          </ns2:idLinea>
          <ns2:nombreLinea>
            <xsl:value-of select="/tns:actualizacionCliente/request/tipoLineaProspecto"/>
          </ns2:nombreLinea>
        </ns2:lineaActualizar>
        <ns2:ObservacionActualizacion>
          <xsl:value-of select="/tns:actualizacionCliente/request/observacionProspecto"/>
        </ns2:ObservacionActualizacion>
      </inp1:actualizacionCliente>
    </inp1:actualizacionCliente>
  </xsl:template>
</xsl:stylesheet>
