<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../OportunidadesBPM.wsdl"/>
      <rootElement name="cargueOportunidades" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../CargaDeOportunidadesEBSAdapter.wsdl"/>
      <rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/CargaDeOportunidadesEBSAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [MON APR 27 17:22:31 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/ProcesosBPM/CargaDeOportunidadesEBSAdapter"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/CargaDeOportunidadesEBSAdapter"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns xsd soap plt ns0 wsdl db xp20 bpws mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <db:InputParameters>
      <db:L_USER_NAME>
        <xsl:value-of select="/tns:cargueOportunidades/request/nombreUsuario"/>
      </db:L_USER_NAME>
      <db:L_DESCRIPTION>
        <xsl:value-of select="/tns:cargueOportunidades/request/nombreOportunidad"/>
      </db:L_DESCRIPTION>
      <db:L_NIT>
        <xsl:value-of select="/tns:cargueOportunidades/request/idCliente"/>
      </db:L_NIT>
      <db:L_SALES_STAGE_ID>
        <xsl:value-of select="number(/tns:cargueOportunidades/request/idEtapaOportunidad)"/>
      </db:L_SALES_STAGE_ID>
      <db:L_STATUS_CODE>
        <xsl:value-of select="/tns:cargueOportunidades/request/idEstadoOportunidad"/>
      </db:L_STATUS_CODE>
      <db:L_TOTAL_AMOUNT>
        <xsl:value-of select="number(/tns:cargueOportunidades/request/monto)"/>
      </db:L_TOTAL_AMOUNT>
      <db:L_CHANNEL_CODE>
        <xsl:value-of select="/tns:cargueOportunidades/request/idCanalEntrada"/>
      </db:L_CHANNEL_CODE>
      <db:L_DECISION_DATE>
        <xsl:value-of select="/tns:cargueOportunidades/request/fechaEstimadaCierre"/>
      </db:L_DECISION_DATE>
      <db:L_CURRENCY_CODE>
        <xsl:value-of select="/tns:cargueOportunidades/request/idTipoMoneda"/>
      </db:L_CURRENCY_CODE>
      <db:L_PROB_OPORCLIE>
        <xsl:value-of select="/tns:cargueOportunidades/request/probabilidadProyecto"/>
      </db:L_PROB_OPORCLIE>
      <db:L_PROB_OPORIMO>
        <xsl:value-of select="/tns:cargueOportunidades/request/probabilidadImocom"/>
      </db:L_PROB_OPORIMO>
      <db:L_TIPO_OPORTUNIDAD>
        <xsl:value-of select="/tns:cargueOportunidades/request/idTipoOportunidad"/>
      </db:L_TIPO_OPORTUNIDAD>
      <db:L_LINE_TBL_BPM>
        <db:L_LINE_TBL_BPM_ITEM>
          <db:INVENTORY_ITEM_ID>
            <xsl:value-of select="number(/tns:cargueOportunidades/request/oportunidadProducto/codigo)"/>
          </db:INVENTORY_ITEM_ID>
          <db:UOM_CODE>
            <xsl:value-of select="/tns:cargueOportunidades/request/oportunidadProducto/unidad"/>
          </db:UOM_CODE>
          <db:QUANTITY>
            <xsl:value-of select="number(/tns:cargueOportunidades/request/oportunidadProducto/cantidad)"/>
          </db:QUANTITY>
          <db:TOTAL_AMOUNT>
            <xsl:value-of select="number(/tns:cargueOportunidades/request/oportunidadProducto/precioLista)"/>
          </db:TOTAL_AMOUNT>
        </db:L_LINE_TBL_BPM_ITEM>
      </db:L_LINE_TBL_BPM>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>
