<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ProcesosBPM.wsdl"/>
      <rootElement name="procesoResultadoVisita" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://192.168.0.25:8001/soa-infra/services/default/comercialProject/VisitaInterface.wsdl"/>
      <rootElement name="resultadoVisita" namespace="http://www.imocom.com.co/soa/xsd/gestionVisita"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 150407.0554.0203) AT [TUE JUN 02 07:19:49 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns1="http://www.imocom.com.co/soa/xsd/oportunidad"
                xmlns:ns2="http://www.imocom.com.co/soa/xsd/prospecto"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns4="http://www.imocom.com.co/soa/xsd/visita"
                xmlns:ns5="http://www.imocom.com.co/soa/xsd/usuario"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://oracle.com/sca/soapservice/ImocomBPM/comercialProject/VisitaInterface"
                xmlns:ns3="http://www.imocom.com.co/soa/xsd/generico"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:inp1="http://www.imocom.com.co/soa/xsd/gestionVisita"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap tns xsd ns1 ns2 ns4 ns5 wsdl ns0 ns3 inp1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <inp1:resultadoVisita>
      <inp1:nombreUsuario>
        <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreUsuario"/>
      </inp1:nombreUsuario>
      <inp1:creacionProspecto>
        <xsl:value-of select="/tns:procesoResultadoVisita/request/creacionProspecto"/>
      </inp1:creacionProspecto>
      <xsl:if test="/tns:procesoResultadoVisita/request">
        <inp1:visita>
          <xsl:if test="/tns:procesoResultadoVisita/request/idClienteVisita">
            <ns4:idCliente>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idClienteVisita"/>
            </ns4:idCliente>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/tipoEventoVisita">
            <ns4:tipoEvento>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/tipoEventoVisita"/>
            </ns4:tipoEvento>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/estadoEventoVisita">
            <ns4:estadoEvento>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/estadoEventoVisita"/>
            </ns4:estadoEvento>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idEventoGeneradorVisita">
            <ns4:idEventoGenerador>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idEventoGeneradorVisita"/>
            </ns4:idEventoGenerador>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/asuntoEventoVisita">
            <ns4:asuntoEvento>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/asuntoEventoVisita"/>
            </ns4:asuntoEvento>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/resultadoEventoVisita">
            <ns4:resultadoEvento>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/resultadoEventoVisita"/>
            </ns4:resultadoEvento>
          </xsl:if>
          <xsl:for-each select="/tns:procesoResultadoVisita/request/oportunidadNota">
            <ns4:oportunidadNota>
              <xsl:if test="idOportunida">
                <ns4:idOportunidad>
                  <xsl:value-of select="idOportunida"/>
                </ns4:idOportunidad>
              </xsl:if>
              <xsl:if test="notaOportunidad">
                <ns4:NotaOportunidad>
                  <xsl:value-of select="notaOportunidad"/>
                </ns4:NotaOportunidad>
              </xsl:if>
            </ns4:oportunidadNota>
          </xsl:for-each>
          <xsl:if test="/tns:procesoResultadoVisita/request/fechaCreacionVisita">
            <ns4:fechaCreacion>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/fechaCreacionVisita"/>
            </ns4:fechaCreacion>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/fechaInicioVisita">
            <ns4:fechaInicio>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/fechaInicioVisita"/>
            </ns4:fechaInicio>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/fechaFinalVisita">
            <ns4:fechaFinal>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/fechaFinalVisita"/>
            </ns4:fechaFinal>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/fechaModificacionVisita">
            <ns4:fechaModificacion>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/fechaModificacionVisita"/>
            </ns4:fechaModificacion>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/fechaRegistroResultadosVisita">
            <ns4:fechaRegistroResultados>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/fechaRegistroResultadosVisita"/>
            </ns4:fechaRegistroResultados>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/ubicacionVisita">
            <ns4:ubicacion>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/ubicacionVisita"/>
            </ns4:ubicacion>
          </xsl:if>
        </inp1:visita>
      </xsl:if>
      <xsl:if test="/tns:procesoResultadoVisita/request">
        <inp1:oportunidad>
          <xsl:if test="/tns:procesoResultadoVisita/request/nombreOportunidadOportunidad">
            <ns1:nombreOportunidad>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreOportunidadOportunidad"/>
            </ns1:nombreOportunidad>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idClienteVisita">
            <ns1:idCliente>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idClienteVisita"/>
            </ns1:idCliente>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/nombreClienteOportunidad">
            <ns1:nombreCliente>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreClienteOportunidad"/>
            </ns1:nombreCliente>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idUsuarioModificadorOportunidad">
            <ns1:idUsuarioModificador>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idUsuarioModificadorOportunidad"/>
            </ns1:idUsuarioModificador>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idTipoOportunidadOportunidad">
            <ns1:idTipoOportunidad>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idTipoOportunidadOportunidad"/>
            </ns1:idTipoOportunidad>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/nombreTipoOportunidadOportunidad">
            <ns1:nombreTipoOportunidad>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreTipoOportunidadOportunidad"/>
            </ns1:nombreTipoOportunidad>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idIncotermOportunidad">
            <ns1:idIncoterm>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idIncotermOportunidad"/>
            </ns1:idIncoterm>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/nombreIncotermOportunidad">
            <ns1:nombreIncoterm>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreIncotermOportunidad"/>
            </ns1:nombreIncoterm>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idTipoMonedaOportunidad">
            <ns1:idTipoMoneda>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idTipoMonedaOportunidad"/>
            </ns1:idTipoMoneda>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idCanalEntradaOportunidad">
            <ns1:idCanalEntrada>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idCanalEntradaOportunidad"/>
            </ns1:idCanalEntrada>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/probabilidadProyectoOportunidad">
            <ns1:probabilidadProyecto>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/probabilidadProyectoOportunidad"/>
            </ns1:probabilidadProyecto>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/probabilidadImocomOportunidad">
            <ns1:probabilidadImocom>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/probabilidadImocomOportunidad"/>
            </ns1:probabilidadImocom>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/observacionOportunidad">
            <ns1:observacion>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/observacionOportunidad"/>
            </ns1:observacion>
          </xsl:if>
          <xsl:for-each select="/tns:procesoResultadoVisita/request/oportunidadProducto">
            <ns1:productoOportunidad>
              <xsl:if test="codigo">
                <ns1:idProducto>
                  <xsl:value-of select="codigo"/>
                </ns1:idProducto>
              </xsl:if>
              <xsl:if test="nombre">
                <ns1:nombreProducto>
                  <xsl:value-of select="nombre"/>
                </ns1:nombreProducto>
              </xsl:if>
              <xsl:if test="marca">
                <ns1:marca>
                  <xsl:value-of select="marca"/>
                </ns1:marca>
              </xsl:if>
              <xsl:if test="modelo">
                <ns1:modelo>
                  <xsl:value-of select="modelo"/>
                </ns1:modelo>
              </xsl:if>
              <xsl:if test="tipoProducto">
                <ns1:tipoProducto>
                  <xsl:value-of select="tipoProducto"/>
                </ns1:tipoProducto>
              </xsl:if>
              <xsl:if test="linea">
                <ns1:centroCostos>
                  <xsl:value-of select="linea"/>
                </ns1:centroCostos>
              </xsl:if>
              <xsl:if test="valorUnitario">
                <ns1:valorUnitario>
                  <xsl:value-of select="valorUnitario"/>
                </ns1:valorUnitario>
              </xsl:if>
              <xsl:if test="cantidad">
                <ns1:cantidad>
                  <xsl:value-of select="cantidad"/>
                </ns1:cantidad>
              </xsl:if>
              <xsl:if test="bodega">
                <ns1:bodega>
                  <xsl:value-of select="bodega"/>
                </ns1:bodega>
              </xsl:if>
              <xsl:if test="unidad">
                <ns1:unidad>
                  <xsl:value-of select="unidad"/>
                </ns1:unidad>
              </xsl:if>
            </ns1:productoOportunidad>
          </xsl:for-each>
          <xsl:if test="/tns:procesoResultadoVisita/request/montoOportunidad">
            <ns1:monto>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/montoOportunidad"/>
            </ns1:monto>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/fechaCreacionVisita">
            <ns1:fechaCreacion>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/fechaCreacionVisita"/>
            </ns1:fechaCreacion>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/fechaEstimadaCierreOportunidad">
            <ns1:fechaEstimadaCierre>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/fechaEstimadaCierreOportunidad"/>
            </ns1:fechaEstimadaCierre>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/fechaModificacionVisita">
            <ns1:fechaModificacion>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/fechaModificacionVisita"/>
            </ns1:fechaModificacion>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idEtapaOportunidadOportunidad">
            <ns1:idEtapaOportunidad>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idEtapaOportunidadOportunidad"/>
            </ns1:idEtapaOportunidad>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/idEstadoOportunidadOportunidad">
            <ns1:idEstadoOportunidad>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idEstadoOportunidadOportunidad"/>
            </ns1:idEstadoOportunidad>
          </xsl:if>
        </inp1:oportunidad>
      </xsl:if>
      <xsl:if test="/tns:procesoResultadoVisita/request">
        <inp1:prospecto>
          <xsl:if test="/tns:procesoResultadoVisita/request/nitClienteProspecto">
            <ns2:nitCliente>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nitClienteProspecto"/>
            </ns2:nitCliente>
          </xsl:if>
          <xsl:if test="/tns:procesoResultadoVisita/request/nombreClienteProspecto">
            <ns2:nombreCliente>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreClienteProspecto"/>
            </ns2:nombreCliente>
          </xsl:if>
          <ns2:nombreRepresentanteLegal>
            <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreRepresentantelegal"/>
          </ns2:nombreRepresentanteLegal>
          <ns2:apellidoRepresentanteLegal>
            <xsl:value-of select="/tns:procesoResultadoVisita/request/apellidoRepresentanteLegal"/>
          </ns2:apellidoRepresentanteLegal>
          <ns2:cedulaRepresentanteLegal>
            <xsl:value-of select="/tns:procesoResultadoVisita/request/cedulaRepresentantelegal"/>
          </ns2:cedulaRepresentanteLegal>
          <ns2:nombreGerenteGeneral>
            <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreGerentelegal"/>
          </ns2:nombreGerenteGeneral>
          <ns2:apellidoGerenteGeneral>
            <xsl:value-of select="/tns:procesoResultadoVisita/request/apellidoGerenteGeneral"/>
          </ns2:apellidoGerenteGeneral>
          <ns2:cedulaGerenteGeneral>
            <xsl:value-of select="/tns:procesoResultadoVisita/request/cedulaGerentelegal"/>
          </ns2:cedulaGerenteGeneral>
          <ns2:contacto>
            <ns2:nombreContacto>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreContactoProspecto"/>
            </ns2:nombreContacto>
            <ns2:apellidoContacto>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/apellidoCliente"/>
            </ns2:apellidoContacto>
            <ns2:idCargo>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idCargoContactoProspecto"/>
            </ns2:idCargo>
            <ns2:cargo>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/cargoContactoProspecto"/>
            </ns2:cargo>
            <ns2:telefonoContacto>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/telefonoContactoProspecto"/>
            </ns2:telefonoContacto>
            <ns2:codigoAreaTelContacto>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/indicativoContacto"/>
            </ns2:codigoAreaTelContacto>
            <ns2:celularContacto>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/celularContactoProspecto"/>
            </ns2:celularContacto>
            <ns2:correoContacto>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/correoContactoProspecto"/>
            </ns2:correoContacto>
          </ns2:contacto>
          <ns2:direccion>
            <xsl:choose>
              <xsl:when test="not(boolean(/tns:procesoResultadoVisita/request/idPaisDireccionProspecto))">
                <ns2:idPais>
                  <xsl:text disable-output-escaping="no">0</xsl:text>
                </ns2:idPais>
              </xsl:when>
              <xsl:when test='/tns:procesoResultadoVisita/request/idPaisDireccionProspecto = ""'>
                <ns2:idPais>
                  <xsl:text disable-output-escaping="no">0</xsl:text>
                </ns2:idPais>
              </xsl:when>
              <xsl:otherwise>
                <ns2:idPais>
                  <xsl:value-of select="/tns:procesoResultadoVisita/request/idPaisDireccionProspecto"/>
                </ns2:idPais>
              </xsl:otherwise>
            </xsl:choose>
            <ns2:nombrePais>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombrePaisDireccionProspecto"/>
            </ns2:nombrePais>
            <xsl:choose>
              <xsl:when test="not(boolean(/tns:procesoResultadoVisita/request/idDepartamentoDireccionProspecto))">
                <ns2:idDepartamento>
                  <xsl:text disable-output-escaping="no">0</xsl:text>
                </ns2:idDepartamento>
              </xsl:when>
              <xsl:when test='/tns:procesoResultadoVisita/request/idDepartamentoDireccionProspecto = ""'>
                <ns2:idDepartamento>
                  <xsl:text disable-output-escaping="no">0</xsl:text>
                </ns2:idDepartamento>
              </xsl:when>
              <xsl:otherwise>
                <ns2:idDepartamento>
                  <xsl:value-of select="/tns:procesoResultadoVisita/request/idDepartamentoDireccionProspecto"/>
                </ns2:idDepartamento>
              </xsl:otherwise>
            </xsl:choose>
            <ns2:nombreDepartamento>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreDepartamentoDireccionProspecto"/>
            </ns2:nombreDepartamento>
            <xsl:choose>
              <xsl:when test="not(boolean(/tns:procesoResultadoVisita/request/idCiudadDireccionProspecto))">
                <ns2:idCiudad>
                  <xsl:text disable-output-escaping="no">0</xsl:text>
                </ns2:idCiudad>
              </xsl:when>
              <xsl:when test='/tns:procesoResultadoVisita/request/idCiudadDireccionProspecto = ""'>
                <ns2:idCiudad>
                  <xsl:text disable-output-escaping="no">0</xsl:text>
                </ns2:idCiudad>
              </xsl:when>
              <xsl:otherwise>
                <ns2:idCiudad>
                  <xsl:value-of select="/tns:procesoResultadoVisita/request/idCiudadDireccionProspecto"/>
                </ns2:idCiudad>
              </xsl:otherwise>
            </xsl:choose>
            <ns2:ciudad>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/ciudadDireccionProspecto"/>
            </ns2:ciudad>
            <ns2:direccion>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/direccionDireccionProspecto"/>
            </ns2:direccion>
            <ns2:telefonoPrincipal>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/telefonoPrincipalDireccionProspecto"/>
            </ns2:telefonoPrincipal>
            <ns2:codigoAreaTelPrincipal>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/indicativo"/>
            </ns2:codigoAreaTelPrincipal>
          </ns2:direccion>
          <ns2:linea>
            <ns2:idLinea>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/idLineaProspecto"/>
            </ns2:idLinea>
            <ns2:nombreLinea>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/tipoLineaProspecto"/>
            </ns2:nombreLinea>
          </ns2:linea>
          <ns2:sectorIndustrial>
            <xsl:choose>
              <xsl:when test="not(boolean(/tns:procesoResultadoVisita/request/idSectorIndustrialProspecto))">
                <ns2:idSectorIndustrial>
                  <xsl:text disable-output-escaping="no">0</xsl:text>
                </ns2:idSectorIndustrial>
              </xsl:when>
              <xsl:when test='/tns:procesoResultadoVisita/request/idSectorIndustrialProspecto = ""'>
                <ns2:idSectorIndustrial>
                  <xsl:text disable-output-escaping="no">0</xsl:text>
                </ns2:idSectorIndustrial>
              </xsl:when>
              <xsl:otherwise>
                <ns2:idSectorIndustrial>
                  <xsl:value-of select="/tns:procesoResultadoVisita/request/idSectorIndustrialProspecto"/>
                </ns2:idSectorIndustrial>
              </xsl:otherwise>
            </xsl:choose>
            <ns2:nombreSectorIndustrial>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/nombreSectorIndustriaProspecto"/>
            </ns2:nombreSectorIndustrial>
          </ns2:sectorIndustrial>
          <xsl:if test="/tns:procesoResultadoVisita/request/observacionProspecto">
            <ns2:observacion>
              <xsl:value-of select="/tns:procesoResultadoVisita/request/observacionProspecto"/>
            </ns2:observacion>
          </xsl:if>
        </inp1:prospecto>
      </xsl:if>
    </inp1:resultadoVisita>
  </xsl:template>
</xsl:stylesheet>
