<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../OportunidadesBPM.wsdl"/>
      <rootElement name="procesoOportunidades" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://192.168.0.25:8001/soa-infra/services/default/comercialProject/OportunidadInterface.wsdl"/>
      <rootElement name="entradaOportunidad" namespace="http://www.imocom.com.co/soa/xsd/gestionOportunidad"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED JUN 03 14:43:24 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns1="http://www.imocom.com.co/soa/xsd/oportunidad"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns2="http://www.imocom.com.co/soa/xsd/generico"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://oracle.com/sca/soapservice/ImocomBPM/comercialProject/OportunidadInterface"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:inp1="http://www.imocom.com.co/soa/xsd/gestionOportunidad"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap tns xsd ns1 wsdl ns2 ns0 inp1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <inp1:entradaOportunidad>
      <inp1:nombreUsuario>
        <xsl:value-of select="/tns:procesoOportunidades/request/nombreUsuario"/>
      </inp1:nombreUsuario>
      <inp1:oportunidad>
        <xsl:if test="/tns:procesoOportunidades/request/nombreOportunidad">
          <ns1:nombreOportunidad>
            <xsl:value-of select="/tns:procesoOportunidades/request/nombreOportunidad"/>
          </ns1:nombreOportunidad>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/idCliente">
          <ns1:idCliente>
            <xsl:value-of select="/tns:procesoOportunidades/request/idCliente"/>
          </ns1:idCliente>
        </xsl:if>
        <ns1:lineaOP>
          <xsl:value-of select="/tns:procesoOportunidades/request/linea"/>
        </ns1:lineaOP>
        <xsl:if test="/tns:procesoOportunidades/request/nombreCliente">
          <ns1:nombreCliente>
            <xsl:value-of select="/tns:procesoOportunidades/request/nombreCliente"/>
          </ns1:nombreCliente>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/idUsuarioModificador">
          <ns1:idUsuarioModificador>
            <xsl:value-of select="/tns:procesoOportunidades/request/idUsuarioModificador"/>
          </ns1:idUsuarioModificador>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/idTipoOportunidad">
          <ns1:idTipoOportunidad>
            <xsl:value-of select="/tns:procesoOportunidades/request/idTipoOportunidad"/>
          </ns1:idTipoOportunidad>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/nombreTipoOportunidad">
          <ns1:nombreTipoOportunidad>
            <xsl:value-of select="/tns:procesoOportunidades/request/nombreTipoOportunidad"/>
          </ns1:nombreTipoOportunidad>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/idIncoterm">
          <ns1:idIncoterm>
            <xsl:value-of select="/tns:procesoOportunidades/request/idIncoterm"/>
          </ns1:idIncoterm>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/nombreIncoterm">
          <ns1:nombreIncoterm>
            <xsl:value-of select="/tns:procesoOportunidades/request/nombreIncoterm"/>
          </ns1:nombreIncoterm>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/idTipoMoneda">
          <ns1:idTipoMoneda>
            <xsl:value-of select="/tns:procesoOportunidades/request/idTipoMoneda"/>
          </ns1:idTipoMoneda>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/idCanalEntrada">
          <ns1:idCanalEntrada>
            <xsl:value-of select="/tns:procesoOportunidades/request/idCanalEntrada"/>
          </ns1:idCanalEntrada>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/probabilidadProyecto">
          <ns1:probabilidadProyecto>
            <xsl:value-of select="/tns:procesoOportunidades/request/probabilidadProyecto"/>
          </ns1:probabilidadProyecto>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/probabilidadImocom">
          <ns1:probabilidadImocom>
            <xsl:value-of select="/tns:procesoOportunidades/request/probabilidadImocom"/>
          </ns1:probabilidadImocom>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/observacion">
          <ns1:observacion>
            <xsl:value-of select="/tns:procesoOportunidades/request/observacion"/>
          </ns1:observacion>
        </xsl:if>
        <xsl:for-each select="/tns:procesoOportunidades/request/oportunidadProducto">
          <ns1:productoOportunidad>
            <xsl:if test="codigo">
              <ns1:idProducto>
                <xsl:value-of select="codigo"/>
              </ns1:idProducto>
            </xsl:if>
            <xsl:if test="nombre">
              <ns1:nombreProducto>
                <xsl:value-of select="nombre"/>
              </ns1:nombreProducto>
            </xsl:if>
            <xsl:if test="marca">
              <ns1:marca>
                <xsl:value-of select="marca"/>
              </ns1:marca>
            </xsl:if>
            <xsl:if test="modelo">
              <ns1:modelo>
                <xsl:value-of select="modelo"/>
              </ns1:modelo>
            </xsl:if>
            <xsl:if test="tipoProducto">
              <ns1:tipoProducto>
                <xsl:value-of select="tipoProducto"/>
              </ns1:tipoProducto>
            </xsl:if>
            <xsl:if test="linea">
              <ns1:centroCostos>
                <xsl:value-of select="linea"/>
              </ns1:centroCostos>
            </xsl:if>
            <xsl:if test="precioListaSinFormato">
              <ns1:valorUnitario>
                <xsl:value-of select="precioListaSinFormato"/>
              </ns1:valorUnitario>
            </xsl:if>
            <xsl:if test="cantidad">
              <ns1:cantidad>
                <xsl:value-of select="cantidad"/>
              </ns1:cantidad>
            </xsl:if>
            <xsl:if test="bodega">
              <ns1:bodega>
                <xsl:value-of select="bodega"/>
              </ns1:bodega>
            </xsl:if>
            <xsl:if test="unidad">
              <ns1:unidad>
                <xsl:value-of select="unidad"/>
              </ns1:unidad>
            </xsl:if>
          </ns1:productoOportunidad>
        </xsl:for-each>
        <xsl:if test="/tns:procesoOportunidades/request/monto">
          <ns1:monto>
            <xsl:value-of select="/tns:procesoOportunidades/request/monto"/>
          </ns1:monto>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/fechaCreacion">
          <ns1:fechaCreacion>
            <xsl:value-of select="/tns:procesoOportunidades/request/fechaCreacion"/>
          </ns1:fechaCreacion>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/fechaEstimadaCierre">
          <ns1:fechaEstimadaCierre>
            <xsl:value-of select="/tns:procesoOportunidades/request/fechaEstimadaCierre"/>
          </ns1:fechaEstimadaCierre>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/fechaModificacion">
          <ns1:fechaModificacion>
            <xsl:value-of select="/tns:procesoOportunidades/request/fechaModificacion"/>
          </ns1:fechaModificacion>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/idEtapaOportunidad">
          <ns1:idEtapaOportunidad>
            <xsl:value-of select="/tns:procesoOportunidades/request/idEtapaOportunidad"/>
          </ns1:idEtapaOportunidad>
        </xsl:if>
        <xsl:if test="/tns:procesoOportunidades/request/idEstadoOportunidad">
          <ns1:idEstadoOportunidad>
            <xsl:value-of select="/tns:procesoOportunidades/request/idEstadoOportunidad"/>
          </ns1:idEstadoOportunidad>
        </xsl:if>
      </inp1:oportunidad>
    </inp1:entradaOportunidad>
  </xsl:template>
</xsl:stylesheet>
