<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="http://192.168.0.33:8001/soa-infra/services/default/Productos/ProductosEBS.wsdl"/>
      <rootElement name="productoCotizableAutomaticamenteResponse" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ProductosEBS.wsdl"/>
      <rootElement name="productoCotizableAutomaticamenteResponse" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED OCT 11 12:06:22 COT 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns xsd soap wsdl bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <tns:productoCotizableAutomaticamenteResponse>
      <productos>
        <codigo>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/codigo"/>
        </codigo>
        <nombre>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/nombre"/>
        </nombre>
        <division>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/division"/>
        </division>
        <linea>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/linea"/>
        </linea>
        <tecnologia>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/tecnologia"/>
        </tecnologia>
        <familia>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/familia"/>
        </familia>
        <marca>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/marca"/>
        </marca>
        <cantidad>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/cantidad"/>
        </cantidad>
        <precioLista>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/precioLista"/>
        </precioLista>
        <moneda>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/moneda"/>
        </moneda>
        <descripcion>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/descripcion"/>
        </descripcion>
        <modelo>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/modelo"/>
        </modelo>
        <tipoProducto>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/tipoProducto"/>
        </tipoProducto>
        <valorUnitario>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/valorUnitario"/>
        </valorUnitario>
        <bodega>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/bodega"/>
        </bodega>
        <unidad>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/unidad"/>
        </unidad>
        <precioListaSinFormato>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/precioListaSinFormato"/>
        </precioListaSinFormato>
        <linkCaracteristicas>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/linkCaracteristicas"/>
        </linkCaracteristicas>
        <linkAccesorios>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/linkAccesorios"/>
        </linkAccesorios>
        <linkVideo>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/linkVideo"/>
        </linkVideo>
        <linkImg>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/linkImg"/>
        </linkImg>
        <organizationId>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/organizationId"/>
        </organizationId>
        <fecha>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/fecha"/>
        </fecha>
        <asesor>
          <xsl:value-of select="/tns:productoCotizableAutomaticamenteResponse/productos/asesor"/>
        </asesor>
      </productos>
    </tns:productoCotizableAutomaticamenteResponse>
  </xsl:template>
</xsl:stylesheet>
