<?binding.jca ConsultaNotasByIdOportundiadAdapter_db.jca?>
<wsdl:definitions name="ConsultaNotasByIdOportundiadAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Notas/ConsultaNotasByIdOportundiadAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaNotasByIdOportundiadAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Notas/ConsultaNotasByIdOportundiadAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConsultaNotasByIdOportundiadAdapter_plt">
        <plt:role name="ConsultaNotasByIdOportundiadAdapter_role">
            <plt:portType name="tns:ConsultaNotasByIdOportundiadAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaNotasByIdOportundiadAdapter" schemaLocation="xsd/ConsultaNotasByIdOportundiadAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaNotasByIdOportundiadAdapterInput_msg">
        <wsdl:part name="ConsultaNotasByIdOportundiadAdapterInput_msg" element="db:ConsultaNotasByIdOportundiadAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaNotasByIdOportundiadAdapterOutputCollection_msg">
        <wsdl:part name="ConsultaNotasByIdOportundiadAdapterOutputCollection" element="db:ConsultaNotasByIdOportundiadAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaNotasByIdOportundiadAdapter_ptt">
        <wsdl:operation name="ConsultaNotasByIdOportundiadAdapter">
            <wsdl:input message="tns:ConsultaNotasByIdOportundiadAdapterInput_msg"/>
            <wsdl:output message="tns:ConsultaNotasByIdOportundiadAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
