SELECT AS_LEADS_ALL.LEAD_ID,
  HZ_PARTIES.JGZZ_FISCAL_CODE NIT,
  HZ_PARTIES.PARTY_NAME Cliente,
  AS_LEADS_ALL.DESCRIPTION Descripcion,
  AS_SALES_STAGES_ALL_TL.DESCRIPTION etapa_oportunidad,
  AS_LEADS_ALL.SALES_STAGE_ID,
  AS_LEADS_ALL.WIN_PROBABILITY,
  JTF_RS_RESOURCE_EXTNS.USER_NAME
FROM AS_LEADS_ALL,
  HZ_PARTIES,
  AS_SALES_STAGES_ALL_TL,
  AS_ACCESSES_ALL,
  JTF_RS_RESOURCE_EXTNS
WHERE AS_LEADS_ALL.CUSTOMER_ID            = HZ_PARTIES.PARTY_ID
AND AS_LEADS_ALL.LEAD_ID                  = AS_ACCESSES_ALL.LEAD_ID
AND AS_ACCESSES_ALL.PERSON_ID             = JTF_RS_RESOURCE_EXTNS.SOURCE_ID
AND AS_SALES_STAGES_ALL_TL.SALES_STAGE_ID = AS_LEADS_ALL.SALES_STAGE_ID
AND AS_SALES_STAGES_ALL_TL.LANGUAGE LIKE 'E'
AND UPPER(AS_LEADS_ALL.DESCRIPTION) LIKE #v_nombre_oportunidad
AND AS_LEADS_ALL.SALES_STAGE_ID LIKE #v_etapa
AND JTF_RS_RESOURCE_EXTNS.USER_NAME LIKE #v_id_asesor