SELECT AS_LEADS_ALL.LEAD_ID,
  HZ_PARTIES.JGZZ_FISCAL_CODE NIT,
  HZ_PARTIES.PARTY_NAME Cliente,
  AS_LEADS_ALL.DESCRIPTION Descripcion,
  AS_SALES_STAGES_ALL_TL.DESCRIPTION etapa_oportunidad,
  AS_LEADS_ALL.SALES_STAGE_ID,
  AS_LEADS_ALL.WIN_PROBABILITY,
  JTF_RS_RESOURCE_EXTNS.USER_NAME
FROM AS_LEADS_ALL,
  HZ_PARTIES,
  AS_SALES_STAGES_ALL_TL,
  FND_USER,
  JTF_RS_RESOURCE_EXTNS
WHERE AS_LEADS_ALL.CUSTOMER_ID            = HZ_PARTIES.PARTY_ID
AND AS_LEADS_ALL.CREATED_BY               = JTF_RS_RESOURCE_EXTNS.USER_ID
AND JTF_RS_RESOURCE_EXTNS.USER_ID         = FND_USER.USER_ID
AND AS_SALES_STAGES_ALL_TL.SALES_STAGE_ID = AS_LEADS_ALL.SALES_STAGE_ID
AND AS_SALES_STAGES_ALL_TL.LANGUAGE LIKE 'E'
AND JGZZ_FISCAL_CODE LIKE #v_nit
AND as_leads_all.attribute4 LIKE #v_probabilidad_exito_1
AND AS_LEADS_ALL.ATTRIBUTE3 LIKE #v_probabilidad_ejecucion
AND AS_LEADS_ALL.SALES_STAGE_ID LIKE #v_etapa
AND FND_USER.USER_NAME LIKE #v_id_asesor