SELECT AS_LEADS_ALL.LEAD_ID,
  HZ_PARTIES.JGZZ_FISCAL_CODE AS NIT,
  HZ_PARTIES.PARTY_NAME,
  AS_LEADS_ALL.CREATION_DATE,
  AS_LEADS_ALL.DESCRIPTION,
  AS_LEADS_ALL.STATUS
FROM AS_LEADS_ALL,
  HZ_PARTIES,
  AS_SALES_LEADS,
  AS_SALES_LEAD_OPPORTUNITY
WHERE AS_LEADS_ALL.CUSTOMER_ID = HZ_PARTIES.PARTY_ID
AND HZ_PARTIES.JGZZ_FISCAL_CODE LIKE #v_nit
AND AS_SALES_LEADS.SALES_LEAD_ID = AS_SALES_LEAD_OPPORTUNITY.SALES_LEAD_ID
AND AS_SALES_LEAD_OPPORTUNITY.OPPORTUNITY_ID = AS_LEADS_ALL.LEAD_ID
AND AS_SALES_LEADS.ASSIGN_TO_PERSON_ID = #v_id_asesor

order BY AS_LEADS_ALL.CREATION_DATE asc
