<?binding.jca ConsultaOportunidadesByNombreEtapaAdapter_db.jca?>
<wsdl:definitions name="ConsultaOportunidadesByNombreEtapaAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Oportunidades/ConsultaOportunidadesByNombreEtapaAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaOportunidadesByNombreEtapaAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Oportunidades/ConsultaOportunidadesByNombreEtapaAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConsultaOportunidadesByNombreEtapaAdapter_plt">
        <plt:role name="ConsultaOportunidadesByNombreEtapaAdapter_role">
            <plt:portType name="tns:ConsultaOportunidadesByNombreEtapaAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaOportunidadesByNombreEtapaAdapter" schemaLocation="xsd/ConsultaOportunidadesByNombreEtapaAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaOportunidadesByNombreEtapaAdapterInput_msg">
        <wsdl:part name="ConsultaOportunidadesByNombreEtapaAdapterInput_msg" element="db:ConsultaOportunidadesByNombreEtapaAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaOportunidadesByNombreEtapaAdapterOutputCollection_msg">
        <wsdl:part name="ConsultaOportunidadesByNombreEtapaAdapterOutputCollection" element="db:ConsultaOportunidadesByNombreEtapaAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaOportunidadesByNombreEtapaAdapter_ptt">
        <wsdl:operation name="ConsultaOportunidadesByNombreEtapaAdapter">
            <wsdl:input message="tns:ConsultaOportunidadesByNombreEtapaAdapterInput_msg"/>
            <wsdl:output message="tns:ConsultaOportunidadesByNombreEtapaAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
