<?binding.jca ConsultaDetalleOportunidadEBSAdapter_db.jca?>
<wsdl:definitions name="ConsultaDetalleOportunidadEBSAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Oportunidades/ConsultaDetalleOportunidadEBSAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaDetalleOportunidadEBSAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Oportunidades/ConsultaDetalleOportunidadEBSAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConsultaDetalleOportunidadEBSAdapter_plt">
        <plt:role name="ConsultaDetalleOportunidadEBSAdapter_role">
            <plt:portType name="tns:ConsultaDetalleOportunidadEBSAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaDetalleOportunidadEBSAdapter" schemaLocation="xsd/ConsultaDetalleOportunidadEBSAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaDetalleOportunidadEBSAdapterInput_msg">
        <wsdl:part name="ConsultaDetalleOportunidadEBSAdapterInput_msg" element="db:ConsultaDetalleOportunidadEBSAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaDetalleOportunidadEBSAdapterOutputCollection_msg">
        <wsdl:part name="ConsultaDetalleOportunidadEBSAdapterOutputCollection" element="db:ConsultaDetalleOportunidadEBSAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaDetalleOportunidadEBSAdapter_ptt">
        <wsdl:operation name="ConsultaDetalleOportunidadEBSAdapter">
            <wsdl:input message="tns:ConsultaDetalleOportunidadEBSAdapterInput_msg"/>
            <wsdl:output message="tns:ConsultaDetalleOportunidadEBSAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
