<?binding.jca ConsultaNotasByNitEBSAdapter_db.jca?>
<wsdl:definitions name="ConsultaNotasByNitEBSAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/NotasEBS/ConsultaNotasByNitEBSAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaNotasByNitEBSAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/NotasEBS/ConsultaNotasByNitEBSAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConsultaNotasByNitEBSAdapter_plt">
        <plt:role name="ConsultaNotasByNitEBSAdapter_role">
            <plt:portType name="tns:ConsultaNotasByNitEBSAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaNotasByNitEBSAdapter" schemaLocation="xsd/ConsultaNotasByNitEBSAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaNotasByNitEBSAdapterInput_msg">
        <wsdl:part name="ConsultaNotasByNitEBSAdapterInput_msg" element="db:ConsultaNotasByNitEBSAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaNotasByNitEBSAdapterOutputCollection_msg">
        <wsdl:part name="ConsultaNotasByNitEBSAdapterOutputCollection" element="db:ConsultaNotasByNitEBSAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaNotasByNitEBSAdapter_ptt">
        <wsdl:operation name="ConsultaNotasByNitEBSAdapter">
            <wsdl:input message="tns:ConsultaNotasByNitEBSAdapterInput_msg"/>
            <wsdl:output message="tns:ConsultaNotasByNitEBSAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
