<?binding.jca ConsultaNotasByIdOportunidadAdapter_db.jca?>
<wsdl:definitions name="ConsultaNotasByIdOportunidadAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/NotasEBS/ConsultaNotasByIdOportunidadAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaNotasByIdOportunidadAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/NotasEBS/ConsultaNotasByIdOportunidadAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConsultaNotasByIdOportunidadAdapter_plt">
        <plt:role name="ConsultaNotasByIdOportunidadAdapter_role">
            <plt:portType name="tns:ConsultaNotasByIdOportunidadAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaNotasByIdOportunidadAdapter" schemaLocation="xsd/ConsultaNotasByIdOportunidadAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaNotasByIdOportunidadAdapterInput_msg">
        <wsdl:part name="ConsultaNotasByIdOportunidadAdapterInput_msg" element="db:ConsultaNotasByIdOportunidadAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaNotasByIdOportunidadAdapterOutputCollection_msg">
        <wsdl:part name="ConsultaNotasByIdOportunidadAdapterOutputCollection" element="db:ConsultaNotasByIdOportunidadAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaNotasByIdOportunidadAdapter_ptt">
        <wsdl:operation name="ConsultaNotasByIdOportunidadAdapter">
            <wsdl:input message="tns:ConsultaNotasByIdOportunidadAdapterInput_msg"/>
            <wsdl:output message="tns:ConsultaNotasByIdOportunidadAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
