insert into recurso (ID_RECURSO,recurso_nombre) values (74,'/vive/pages/secured/mobile/productos/consultor-productos.jsf');
insert into ROL_RECURSO (ID_ROL_RECURSO, id_rol, id_recurso) values (100,1,74);
insert into menu (ID_MENU,MENU_NOMBRE,MENU_ACCION,MENU_ORDEN) VALUES (27,'Consulta Producto','outcome:productos-consulta',1);
INSERT INTO ROL_MENU (ID_ROL_MENU,ID_ROL,ID_MENU) VALUES (47,1,27);
--
CREATE TABLE "MARCA" 
(
	"ID_MARCA" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR(100),
	"LINEA" VARCHAR2(100),
	 CONSTRAINT "PK_MARCA" PRIMARY KEY ("ID_MARCA")
);
--
CREATE TABLE "MODELO" 
(
	"ID_MODELO" NUMBER NOT NULL ENABLE, 
	"NOMBRE"   VARCHAR(100),
	"ID_MARCA" NUMBER NOT NULL,
	 CONSTRAINT "PK_MODELO" PRIMARY KEY ("ID_MODELO"),
	 CONSTRAINT "FK_MARCA" FOREIGN KEY ("ID_MARCA")
	  REFERENCES "MARCA" ("ID_MARCA")
);		
--
CREATE TABLE "MODELO" 
(
	"ID_MODELO" NUMBER NOT NULL ENABLE, 
	"NOMBRE"   VARCHAR(100),
	"ID_MARCA" NUMBER NOT NULL,
	 CONSTRAINT "PK_MODELO" PRIMARY KEY ("ID_MODELO"),
	 CONSTRAINT "FK_MARCA" FOREIGN KEY ("ID_MARCA")
	  REFERENCES "MARCA" ("ID_MARCA")
);	
--
CREATE TABLE "TIPO_PRODUCTO" 
(
	"ID_TIPO" NUMBER NOT NULL ENABLE, 
	"NOMBRE"   VARCHAR(100),
	CONSTRAINT "PK_TIPO_PRODUCTO" PRIMARY KEY ("ID_TIPO")
);
--	
CREATE TABLE "MONEDA" 
(
	"ID_MONEDA" NUMBER NOT NULL ENABLE, 
	"NOMBRE"   VARCHAR(100),
    CONSTRAINT "PK_MONEDA" PRIMARY KEY ("ID_MONEDA")
);
--
CREATE TABLE "PRODUCTO"
(
	"ID_PRODUCTO" NUMBER NOT NULL ENABLE, 
	"ID_TIPO" NUMBER NOT NULL ENABLE, 
	"CODIGO"  VARCHAR(100),
	"DESCRIPCION" VARCHAR(200),
	"ID_MODELO" NUMBER NOT NULL ENABLE,
	"ID_MONEDA" NUMBER NOT NULL ENABLE,
	"PRECIO"  NUMBER (16,4),
	"ESTADO"  VARCHAR(10),
	"COTIZABLE"  INT,
	"CATALOGO"  VARCHAR(200),
	CONSTRAINT "PK_PRODUCTO" PRIMARY KEY ("ID_PRODUCTO"),
	CONSTRAINT "FK_TIPO_PRODUCTO" FOREIGN KEY ("ID_TIPO") REFERENCES "TIPO_PRODUCTO" ("ID_TIPO"),
	CONSTRAINT "FK_ID_MODELO" FOREIGN KEY ("ID_MODELO") REFERENCES "MODELO" ("ID_MODELO"),
	CONSTRAINT "FK_ID_MONEDA" FOREIGN KEY ("ID_MONEDA") REFERENCES "MONEDA" ("ID_MONEDA")	
); 