<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsultarContactosPorCliente.wsdl"/>
      <rootElement name="ConsultarContactosPorClienteOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContactosPorCliente"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ClientesEBS.wsdl"/>
      <rootElement name="consultarContactosPorClienteResponse" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 150407.0554.0203) AT [TUE JUN 02 18:53:36 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:tns="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContactosPorCliente"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns plt xsd wsdl db soap bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <tns:consultarContactosPorClienteResponse>
      <return>
        <xsl:for-each select="/db:ConsultarContactosPorClienteOutputCollection/db:ConsultarContactosPorClienteOutput">
          <contactos>
            <nombre>
              <xsl:value-of select="db:party_name"/>
            </nombre>
            <cargo>
              <xsl:value-of select="db:ROLE"/>
            </cargo>
            <telefono>
              <xsl:value-of select="db:PRIMARY_PHONE_NUMBER"/>
            </telefono>
            <celular>
              <xsl:value-of select="db:CELULAR"/>
            </celular>
            <correo>
              <xsl:value-of select="db:EMAIL_ADDRESS"/>
            </correo>
            <id>
              <xsl:value-of select="db:PARTY_ID"/>
            </id>
            <apellido>
              <xsl:value-of select="db:PERSON_LAST_NAME"/>
            </apellido>
          </contactos>
        </xsl:for-each>
      </return>
    </tns:consultarContactosPorClienteResponse>
  </xsl:template>
</xsl:stylesheet>
