<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../GeoConsultaAdapter.wsdl"/>
      <rootElement name="GeoConsultaAdapterOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GeoConsultaAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ClientesEBS.wsdl"/>
      <rootElement name="geoConsultaResponse" namespace="http://com.imocom.intelcom.ws.ebs.interfaces/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 150407.0554.0203) AT [FRI MAY 22 14:16:09 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosEBS/Clientes/GeoConsultaAdapter"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GeoConsultaAdapter"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://com.imocom.intelcom.ws.ebs.interfaces/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns plt wsdl db xsd soap ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns0:geoConsultaResponse>
      <return>
        <xsl:for-each select="/db:GeoConsultaAdapterOutputCollection/db:GeoConsultaAdapterOutput">
          <clientes>
            <partyId>
              <xsl:value-of select="db:PARTY_ID"/>
            </partyId>
            <partyNumber>
              <xsl:value-of select="db:PARTY_NUMBER"/>
            </partyNumber>
            <nombreCliente>
              <xsl:value-of select="db:NOMBRE"/>
            </nombreCliente>
            <fechaCreacion>
              <xsl:value-of select="db:fecha_creacion"/>
            </fechaCreacion>
            <nitCliente>
              <xsl:value-of select="db:NIT"/>
            </nitCliente>
            <ciudad>
              <xsl:value-of select="db:CIUDAD"/>
            </ciudad>
            <departamento>
              <xsl:value-of select="db:DEPARTAMENTO"/>
            </departamento>
            <urlCliente>
              <xsl:value-of select="db:URL"/>
            </urlCliente>
            <correoCliente>
              <xsl:value-of select="db:CORREO"/>
            </correoCliente>
            <direccionPpal>
              <xsl:value-of select="db:DIRECCION"/>
            </direccionPpal>
            <telefonoPpal>
              <xsl:value-of select="db:TELEFONO"/>
            </telefonoPpal>
            <tipoCliente>
              <xsl:value-of select="db:TIPO_CLIENTE"/>
            </tipoCliente>
            <diasSinVisita>
              <xsl:value-of select="db:diasSinVisita"/>
            </diasSinVisita>
            <pais>
              <xsl:value-of select="db:PAIS"/>
            </pais>
            <coordClienteLat>
              <xsl:value-of select='substring-before(db:LONGITUD,",")'/>
            </coordClienteLat>
            <coordClienteLong>
              <xsl:value-of select='substring-after(db:LONGITUD,",")'/>
            </coordClienteLong>
            <semaforo>
              <xsl:value-of select="xp20:upper-case(db:SEMAFORO)"/>
            </semaforo>
          </clientes>
        </xsl:for-each>
      </return>
    </ns0:geoConsultaResponse>
  </xsl:template>
</xsl:stylesheet>
