
package com.imocom.intelcom.ws.ebs.interfaces;

import com.imocom.intelcom.ws.ebs.vo.entities.AsignacionCanalesVO;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AsignacionAutomaticaOportunidadesPortType", targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/AsignacionAutomaticaOportunidades")
public interface IAsignacionAutomaticaOportunidades {


    /**
     * 
     * @param asignacionCanales 
     */
    @WebMethod(action = "start")
    public void start(@WebParam(name = "AsignacionCanales", targetNamespace = "") AsignacionCanalesVO asignacionCanales);
}
