SELECT CUSTOMER_NAME AS NOMBRE_CLIENTE,
  CUSTOMER_NUMBER,
  CUSTOMER_ID,
  (SELECT cod.CLASS_CODE
  FROM hz_code_assignments cod
  WHERE cod.owner_table_id LIKE SUBSTR(customer_id,1,9)
  AND cod.owner_table_name = 'HZ_PARTIES'
  AND cod.class_category   = 'Estado del Cliente'
  ) AS TIPOCLIE,
  CUPO_CREDITO,
  NUMERO_DOC,
  TIPO_DOC,
  FECHA_VENCIMIENTO,
  DIAS_VENCIDOS,
  PORVENC0_30+PORVENC31_X+VENC0_30+VENC31_60+VENC61_90+VENC91_X AS sub_TOTAL_CARTERA,
  VENC0_30   +VENC31_60+VENC61_90+VENC91_X                      AS VALOR_VENCIDO,
  PORVENC0_30+PORVENC31_X                                       AS VALOR_POR_VENCER,
  VALOR_CARTERA,
  LINEA
FROM IMCM_CARTERA_EDADES_LINEAS_VM2
WHERE SUBSTR(CUSTOMER_NUMBER,1,9) = #v_nit