SELECT
  COMPANIA,
  VENDEDOR,
  ESTADO_ENVIO,
  CUSTOMER_ID,
  CUSTOMER_NAME,
  CLIENTE_ENVIO,
  CUSTOMER_NUMBER,
  TIPOCLIE,
  TIPO_DOC,
  NUMERO_DOC,
  MONEDA,
  VALOR_ORIGINAL_PROG,
  FECHA_IMPRESION,
  FECHA_TRANSACCION,
  FECHA_VENCIMIENTO,
  DIAS_VENCIDOS,
  VALOR_CARTERA,
  CARTERAVENCIDA,
  ANTICIPOS,
  RECAUDO,
  CUPO_CREDITO
FROM IMCM_CARTERA_EDADES_LINEAS_V2
WHERE CUSTOMER_NUMBER LIKE ('%'||860350697||'%')
AND vendedor like '%REINA REINA WILSON%'
AND tipo_doc like '%Factura%'


WHERE CUSTOMER_NUMBER LIKE ('%'||#v_nit||'%')
WHERE CUSTOMER_NUMBER LIKE ('%'||860350697||'%')